services:
    sonata.admin.season:
        class: AppBundle\Admin\SeasonAdmin
        arguments: [ ~, AppBundle\Entity\Season, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Series", label: "Season" }
    sonata.admin.series:
        class: AppBundle\Admin\SeriesAdmin
        arguments: [ ~, AppBundle\Entity\Series, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Series", label: "Series" }
    sonata.admin.episode:
        class: AppBundle\Admin\EpisodeAdmin
        arguments: [ ~, AppBundle\Entity\Episode, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Series", label: "Episode" }
    sonata.admin.genre:
        class: AppBundle\Admin\GenreAdmin
        arguments: [ ~, AppBundle\Entity\Genre, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Series", label: "Genre" }
    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "User" }
    sonata.admin.review:
        class: AppBundle\Admin\ReviewAdmin
        arguments: [ ~, AppBundle\Entity\Review, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Review" }
